/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Form.Xuli.KetNoiDB;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author StarScream
 */
public class SuaDV_Form extends javax.swing.JDialog {

    /** Creates new form SuaDV_Form */
    private HashMap bangDV = new HashMap();
    private HashMap listDichVuDangSuDung = new HashMap();
    private String luuThoiGian = null,
            luuMaNhanVien = null,
            luuMoTa = null;

    public SuaDV_Form(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadData();
    }

    public void loadDataComboxDV() {
        jCBDichVu.removeAllItems();
        bangDV.clear();
        String sql = "select MaDV,TenDV from DICHVU";
        Connection ketNoi = KetNoiDB.getConnection();
        try {
            Statement st = ketNoi.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                bangDV.put(rs.getString("TenDV"), rs.getString("MaDV"));
                jCBDichVu.addItem(rs.getString("TenDV"));
            }
            st.close();
            rs.close();
            ketNoi.close();
        } catch (Exception e) {
        }

    }

    public String getMaDV(String TenDV) {
        String MaDV = "";
        for (Object i : bangDV.keySet()) {
            if (i.equals(TenDV)) {
                MaDV = (String) bangDV.get(i);
            }
        }
        return MaDV;
    }

    public String traVeTenDichVu(String maDV) {
        for (Object i : bangDV.keySet()) {
            if (maDV.equals(bangDV.get(i))) {
                return (String) i;
            }
        }
        return null;
    }

    public static String traVeMaNhanVien(String s) {
        String sql = "select MaNV from CT_SDDV where BienSoXe = '" + s + "'";
        Connection ketNoi = KetNoiDB.getConnection();
        String tamp = null;
        try {
            Statement st = ketNoi.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                tamp = rs.getString("MaNV");
            }
            st.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException e) {
        }
        return tamp;
    }

    public void loadDataVaoBangDichVu() {
        String sql = "select MaNV,MaDV,NgayGioLamDV,MoTa from CT_SDDV where BienSoXe = '" + NVSX_Form.dataSuaDichVu + "'";
        Connection ketNoi = KetNoiDB.getConnection();
        listDichVuDangSuDung.clear();
        try {
            Statement st = ketNoi.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                luuMaNhanVien = rs.getString("MaNV");
                listDichVuDangSuDung.put(traVeTenDichVu(rs.getString("MaDV")), rs.getString("MaDV"));
                luuThoiGian = rs.getString("NgayGioLamDV");
                luuMoTa = rs.getString("MoTa");
            }
            st.close();
            rs.close();
            ketNoi.close();
        } catch (SQLException e) {
        }

    }

    public void themDichVuVaoBang() {
        DefaultTableModel model = (DefaultTableModel) tbDichVu.getModel();
        model.setRowCount(0);
        Vector thayThe;
        int count = 0;
        for (Object i : listDichVuDangSuDung.keySet()) {
            thayThe = new Vector();
            count++;
            thayThe.addElement(count);
            thayThe.addElement(listDichVuDangSuDung.get(i));
            thayThe.addElement(i);
            model.addRow(thayThe);
        }
    }

    public void loadData() {
        jBienSoXe.setText(NVSX_Form.dataSuaDichVu);
        jHoTen.setText(PhanCongForm.getTenNhanVien(traVeMaNhanVien(NVSX_Form.dataSuaDichVu)));
        loadDataComboxDV();
        loadDataVaoBangDichVu();
        themDichVuVaoBang();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jHoTen = new javax.swing.JTextField();
        jBienSoXe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDichVu = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jCBDichVu = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHỈNH SỬA DỊCH VỤ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Biển số xe:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Họ tên NVBD:");

        jHoTen.setEditable(false);
        jHoTen.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jBienSoXe.setEditable(false);
        jBienSoXe.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        tbDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã dịch vụ", "Dịch vụ"
            }
        ));
        tbDichVu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbDichVuKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbDichVu);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Danh sách dịch vụ đang tiếp nhận:");

        jCBDichVu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCBDichVu.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setText("THÊM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Dịch vụ:");

        jToggleButton1.setText("Lưu");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Huỷ");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jHoTen)
                    .addComponent(jBienSoXe)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: them dich vu
        String tam = (String) jCBDichVu.getSelectedItem();
        listDichVuDangSuDung.put(tam, getMaDV(tam));
        themDichVuVaoBang();

    }//GEN-LAST:event_jButton1ActionPerformed
    public String chonDichVuTrongBangCanXoa() {
        int index = tbDichVu.getSelectedRow();
        return (String) tbDichVu.getValueAt(index, 2);
    }
    private void tbDichVuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDichVuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            String tem = chonDichVuTrongBangCanXoa();
            if (tem == "") {
                JOptionPane.showMessageDialog(rootPane, "Chọn dịch vụ để xóa");
            } else {
                int check = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa dịch vụ");
                if (check == 0) {
                    listDichVuDangSuDung.remove(tem);
                }
            }
            themDichVuVaoBang();
        }
    }//GEN-LAST:event_tbDichVuKeyPressed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
    public void updateDichVu() {
        xoaTruocKhiSua();
        int check = 0;
        for (Object i : listDichVuDangSuDung.keySet()) {
            String MaDV = (String) listDichVuDangSuDung.get(i);
            Connection ketNoi = KetNoiDB.getConnection();
            try {
                String sql = "INSERT INTO CT_SDDV(BienSoXe,MaNV,MaDV,NgayGiolamDV,NgayGioHT,MoTa)  VALUES(?,?,?,?,?,?)";
                PreparedStatement ps = ketNoi.prepareStatement(sql);
                ps.setString(1, NVSX_Form.dataSuaDichVu);
                ps.setString(2, luuMaNhanVien);
                ps.setString(3, MaDV);
                ps.setString(4, luuThoiGian);
                ps.setString(5, null);
                ps.setString(6, luuMoTa);
                check = ps.executeUpdate();
                ps.close();
                ketNoi.close();
            } catch (Exception e) {
            }
        }
        if (check > 0) {
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi! Sửa không thành công");
        }
    }

    public void xoaTruocKhiSua() {
        String sql = "Delete from CT_SDDV where BienSoXe = '" + NVSX_Form.dataSuaDichVu + "'";
        Connection ketNoi = KetNoiDB.getConnection();
        try {
            PreparedStatement st = ketNoi.prepareStatement(sql);
            st.executeUpdate();
            st.close();
        } catch (Exception e) {
        }

    }
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        updateDichVu();
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaDV_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaDV_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaDV_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaDV_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaDV_Form dialog = new SuaDV_Form(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBienSoXe;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBDichVu;
    private javax.swing.JTextField jHoTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable tbDichVu;
    // End of variables declaration//GEN-END:variables
}
