/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Form.Xuli.KetNoiDB;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author StarScream
 */
public class TTCN_From extends javax.swing.JDialog {

    /** Creates new form TTCN_From */
    public TTCN_From(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadLuongVaCong(ycNam.getYear(), mcThang.getMonth()+1);
        loadDB();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbAnh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        lbMNV = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbDanToc = new javax.swing.JLabel();
        lbQueQuan = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbCMND = new javax.swing.JLabel();
        lbChucVu = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbTienLuong = new javax.swing.JLabel();
        lbNgayKi = new javax.swing.JLabel();
        lbNgayHH = new javax.swing.JLabel();
        lbSoNgayCong = new javax.swing.JLabel();
        ycNam = new com.toedter.calendar.JYearChooser();
        mcThang = new com.toedter.calendar.JMonthChooser();
        btnXem = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 54, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 160));

        jPanel2.setBackground(new java.awt.Color(137, 184, 152));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Họ và tên:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quê quán:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới tính:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã nhân viên:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CMND:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dân tộc:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SDT:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Địa chỉ:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 60, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Chức vụ:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ngày sinh:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        lbDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        lbDiaChi.setText("jLabel14");
        jPanel2.add(lbDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 650, -1));

        lbMNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMNV.setForeground(new java.awt.Color(255, 255, 255));
        lbMNV.setText("jLabel14");
        jPanel2.add(lbMNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 190, -1));

        lbGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGioiTinh.setForeground(new java.awt.Color(255, 255, 255));
        lbGioiTinh.setText("jLabel14");
        jPanel2.add(lbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, -1));

        lbDanToc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDanToc.setForeground(new java.awt.Color(255, 255, 255));
        lbDanToc.setText("jLabel14");
        jPanel2.add(lbDanToc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, -1));

        lbQueQuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbQueQuan.setForeground(new java.awt.Color(255, 255, 255));
        lbQueQuan.setText("jLabel14");
        jPanel2.add(lbQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 640, -1));

        lbHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTen.setText("jLabel14");
        jPanel2.add(lbHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 210, -1));

        lbCMND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCMND.setForeground(new java.awt.Color(255, 255, 255));
        lbCMND.setText("jLabel14");
        jPanel2.add(lbCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 220, -1));

        lbChucVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lbChucVu.setText("jLabel14");
        jPanel2.add(lbChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 210, -1));

        lbNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNgaySinh.setForeground(new java.awt.Color(255, 255, 255));
        lbNgaySinh.setText("jLabel14");
        jPanel2.add(lbNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 190, -1));

        lbSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSDT.setForeground(new java.awt.Color(255, 255, 255));
        lbSDT.setText("jLabel14");
        jPanel2.add(lbSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 190, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("THÔNG TIN CÁ NHÂN");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 530, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 690, 340));

        jPanel3.setBackground(new java.awt.Color(137, 184, 152));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ngày kí hợp đồng:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Ngày hết hạn hợp đồng:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tiền lương thực lĩnh:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Số ngày công:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        lbTienLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTienLuong.setForeground(new java.awt.Color(255, 255, 255));
        lbTienLuong.setText("jLabel29");
        jPanel3.add(lbTienLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 170, -1));

        lbNgayKi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNgayKi.setForeground(new java.awt.Color(255, 255, 255));
        lbNgayKi.setText("jLabel29");
        jPanel3.add(lbNgayKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 170, -1));

        lbNgayHH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNgayHH.setForeground(new java.awt.Color(255, 255, 255));
        lbNgayHH.setText("jLabel29");
        jPanel3.add(lbNgayHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, -1));

        lbSoNgayCong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSoNgayCong.setForeground(new java.awt.Color(255, 255, 255));
        lbSoNgayCong.setText("jLabel29");
        jPanel3.add(lbSoNgayCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 170, -1));
        jPanel3.add(ycNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 70, 30));
        jPanel3.add(mcThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, 30));

        btnXem.setBackground(new java.awt.Color(254, 206, 171));
        btnXem.setText("XEM");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });
        jPanel3.add(btnXem, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 13, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 850, 110));

        btnOK.setBackground(new java.awt.Color(254, 206, 171));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
       
        loadLuongVaCong(ycNam.getYear(), mcThang.getMonth()+1);
        
    }//GEN-LAST:event_btnXemActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadDB() {
        String sql = "select HoTen,CONVERT(varchar, NgaySinh, 105) as NgaySinh,"
                + " GioiTinh,ChucVu,TenCV,SDT,CMND,DanToc,DiaChi,QueQuan,"
                + "CONVERT(varchar, NgayKy, 105) as NgayKy,CONVERT(varchar, HanHD, 105) as HanHD,"
                + "HinhAnh from NHANVIEN,CHUCVU,HOPDONG where NHANVIEN.ChucVu=CHUCVU.MaCV"
                + " and NHANVIEN.MaNV=HOPDONG.MaNV"
                + " and NHANVIEN.MaNV= '" + LoginForm.MaNV + "'";
        try {
            Connection con = KetNoiDB.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                lbMNV.setText(LoginForm.MaNV);
                lbNgaySinh.setText(rs.getString("NgaySinh"));
                lbHoTen.setText(rs.getString("HoTen"));
                lbSDT.setText(rs.getString("SDT"));
                lbCMND.setText(rs.getString("CMND"));
                lbDanToc.setText(rs.getString("DanToc"));
                lbDiaChi.setText(rs.getString("DiaChi"));
                lbChucVu.setText(rs.getString("TenCV"));
                lbQueQuan.setText(rs.getString("QueQuan"));
                lbNgayKi.setText(rs.getString("NgayKy"));
                lbNgayHH.setText(rs.getString("HanHD"));
                byte[] img = rs.getBytes("HinhAnh");
                if (img!=null) {
                ImageIcon imageicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbAnh.getWidth(), lbAnh.getHeight(), Image.SCALE_SMOOTH));
                lbAnh.setIcon(imageicon);
                }
                switch (rs.getInt("GioiTinh")) {
                    case 0 ->
                        lbGioiTinh.setText("Nam");
                    case 1 ->
                        lbGioiTinh.setText("Nữ");
                    case 2 ->
                        lbGioiTinh.setText("Khác");
                }
               

            }
            rs.close();
            st.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(TTNV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadLuongVaCong(int nam,int thang){
        String sql ="select NgayCong,THUCLINH " +
                    "from CONG,THANHTOANLUONG " +
                    "where CONG.MaNV=THANHTOANLUONG.MaNV and Thang="+thang+" and Nam="+nam 
                    + "and CONG.MaNV='"+LoginForm.MaNV+"'";
        Connection con=KetNoiDB.getConnection();
        try {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                    lbSoNgayCong.setText(rs.getString("NgayCong"));
                    lbTienLuong.setText(rs.getString("THUCLINH"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TTCN_From.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTCN_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTCN_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTCN_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTCN_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TTCN_From dialog = new TTCN_From(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnXem;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbCMND;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbDanToc;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMNV;
    private javax.swing.JLabel lbNgayHH;
    private javax.swing.JLabel lbNgayKi;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbQueQuan;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbSoNgayCong;
    private javax.swing.JLabel lbTienLuong;
    private com.toedter.calendar.JMonthChooser mcThang;
    private com.toedter.calendar.JYearChooser ycNam;
    // End of variables declaration//GEN-END:variables
}
